/**
 * MediCare Pro — Fictional seed data (demo only, no real patient information).
 * Used by scripts/seed.js to populate Firestore. Also referenced by the site's
 * fallback data so the demo works before Firebase is configured.
 */

// ---------------------------------------------------------------------------
// STAFF — one entry per Firebase Auth user. Passwords are the same demo
// credentials the site already documented (brute-force lab, login fallback).
// The seed script creates the Auth users and fills in `uid`.
// ---------------------------------------------------------------------------
const STAFF = [
  { username: 'admin',       email: 'admin@medicare.ph',      password: 'admin123',  name: 'Dr. Admin',    role: 'Administrator', department: 'Administration' },
  { username: 'doctor',      email: 'santos@medicare.ph',     password: 'password1', name: 'Dr. Santos',   role: 'Physician',      department: 'Cardiology' },
  { username: 'nurse',       email: 'reyes@medicare.ph',      password: 'nurse123',  name: 'Nurse Reyes',  role: 'Nurse',          department: 'Cardiology' },
  { username: 'radiologist', email: 'bautista@medicare.ph',   password: 'xray2024',  name: 'Dr. Bautista', role: 'Radiologist',    department: 'Radiology' },
  { username: 'labtech',     email: 'cruz@medicare.ph',       password: 'lab2024',   name: 'M. Cruz',      role: 'Lab Technician', department: 'Laboratory' },
];

// ---------------------------------------------------------------------------
// PATIENTS — 50 fictional records distributed across departments.
// id: numeric (1-50) so the SQL-injection lab queries (id = '1') keep working.
// ---------------------------------------------------------------------------
const PATIENTS = [
  { id: 1,  name: 'Maria Santos',        dob: '1968-05-12', gender: 'F', department: 'Cardiology',    ward: 'Cardiology Ward',    room: '101', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Hypertension',           medications: 'Amlodipine 5mg daily',            allergies: ['Penicillin'], notes: 'Monthly checkups required.' },
  { id: 2,  name: 'Juan Dela Cruz',      dob: '1978-03-15', gender: 'M', department: 'Endocrinology', ward: 'Endocrinology Ward', room: '214', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Diabetes Type 2',         medications: 'Metformin 500mg BID',            allergies: ['None'], notes: 'Insulin dependent. Monitor glucose daily.' },
  { id: 3,  name: 'Ana Reyes',           dob: '1990-07-22', gender: 'F', department: 'Pulmonology',   ward: 'Pulmonology Ward',   room: '305', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'Bronchial Asthma',        medications: 'Salbutamol inhaler',             allergies: ['Dust mites'], notes: 'Carry inhaler. Avoid allergens.' },
  { id: 4,  name: 'Pedro Bautista',      dob: '1955-11-02', gender: 'M', department: 'Rheumatology',  ward: 'Rheumatology Ward',  room: '118', status: 'Outpatient', physician: 'Dr. Mercado',  diagnosis: 'Rheumatoid Arthritis',    medications: 'NSAIDs as needed',               allergies: ['None'], notes: 'Physical therapy twice weekly.' },
  { id: 5,  name: 'Rosario Garcia',      dob: '1962-01-30', gender: 'F', department: 'Cardiology',    ward: 'Cardiology Ward',    room: '102', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Coronary Artery Disease',  medications: 'Aspirin 75mg daily',             allergies: ['None'], notes: 'Restrict strenuous activity.' },
  { id: 6,  name: 'Jose Ramirez',        dob: '1971-09-18', gender: 'M', department: 'Cardiology',    ward: 'Cardiology Ward',    room: '103', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Atrial Fibrillation',     medications: 'Warfarin 5mg',                   allergies: ['None'], notes: 'Monitor INR weekly.' },
  { id: 7,  name: 'Liza Mendoza',        dob: '1985-04-25', gender: 'F', department: 'Cardiology',    ward: 'Cardiology Ward',    room: '104', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Congestive Heart Failure', medications: 'Furosemide 40mg',                 allergies: ['Iodine'], notes: 'Daily weight monitoring.' },
  { id: 8,  name: 'Ramon Villanueva',    dob: '1949-12-08', gender: 'M', department: 'Cardiology',    ward: 'Cardiology Ward',    room: '105', status: 'Outpatient', physician: 'Dr. Santos',   diagnosis: 'Hypertension',           medications: 'Losartan 50mg',                  allergies: ['None'], notes: 'BP log review monthly.' },
  { id: 9,  name: 'Carla Fernandez',     dob: '1992-06-14', gender: 'F', department: 'Cardiology',    ward: 'Cardiology Ward',    room: '106', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Arrhythmia',               medications: 'Beta blockers',                  allergies: ['None'], notes: 'Holter monitor 48h.' },
  { id: 10, name: 'Miguel Torres',       dob: '1980-02-27', gender: 'M', department: 'Cardiology',    ward: 'Cardiology Ward',    room: '107', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Hypertension',           medications: 'Amlodipine 10mg',                allergies: ['None'], notes: 'Diet consult scheduled.' },
  { id: 11, name: 'Elena Aquino',        dob: '1975-08-09', gender: 'F', department: 'Endocrinology', ward: 'Endocrinology Ward', room: '201', status: 'Outpatient', physician: 'Dr. Mercado',  diagnosis: 'Hypothyroidism',          medications: 'Levothyroxine 100mcg',           allergies: ['None'], notes: 'TSH check quarterly.' },
  { id: 12, name: 'Ricardo Navarro',     dob: '1969-10-21', gender: 'M', department: 'Endocrinology', ward: 'Endocrinology Ward', room: '202', status: 'Admitted',   physician: 'Dr. Mercado',  diagnosis: 'Diabetes Type 2',         medications: 'Metformin + insulin',            allergies: ['None'], notes: 'Endocrine consult.' },
  { id: 13, name: 'Sofia Castillo',      dob: '1988-03-03', gender: 'F', department: 'Endocrinology', ward: 'Endocrinology Ward', room: '203', status: 'Outpatient', physician: 'Dr. Mercado',  diagnosis: 'PCOS',                       medications: 'Metformin 500mg',                allergies: ['None'], notes: 'Follow up in 3 months.' },
  { id: 14, name: 'Andres Domingo',      dob: '1958-05-17', gender: 'M', department: 'Endocrinology', ward: 'Endocrinology Ward', room: '204', status: 'Admitted',   physician: 'Dr. Mercado',  diagnosis: 'Diabetes Type 1',         medications: 'Insulin pump',                   allergies: ['None'], notes: 'Endocrine consult.' },
  { id: 15, name: 'Teresa Flores',       dob: '1972-12-29', gender: 'F', department: 'Pulmonology',   ward: 'Pulmonology Ward',   room: '301', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'COPD',                      medications: 'Bronchodilators',                allergies: ['None'], notes: 'Oxygen saturation monitoring.' },
  { id: 16, name: 'Marco Reyes',         dob: '1986-09-05', gender: 'M', department: 'Pulmonology',   ward: 'Pulmonology Ward',   room: '302', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'Pneumonia',                 medications: 'Antibiotics IV',                 allergies: ['Sulfa'], notes: 'Chest physiotherapy daily.' },
  { id: 17, name: 'Julia Salvador',      dob: '1995-01-19', gender: 'F', department: 'Pulmonology',   ward: 'Pulmonology Ward',   room: '303', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'Asthma',                     medications: 'Salbutamol',                     allergies: ['Pollen'], notes: 'Peak flow diary.' },
  { id: 18, name: 'Emilio Cruz',         dob: '1964-07-08', gender: 'M', department: 'Rheumatology',  ward: 'Rheumatology Ward',  room: '119', status: 'Outpatient', physician: 'Dr. Mercado',  diagnosis: 'Osteoarthritis',            medications: 'NSAIDs',                         allergies: ['None'], notes: 'Joint exercises prescribed.' },
  { id: 19, name: 'Beatriz Santos',      dob: '2018-04-11', gender: 'F', department: 'Pediatrics',    ward: 'Pediatrics Ward',    room: '401', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'Acute Bronchitis',          medications: 'Antibiotics',                    allergies: ['None'], notes: 'Pediatric follow-up.' },
  { id: 20, name: 'Carlos Mercado',      dob: '2015-11-23', gender: 'M', department: 'Pediatrics',    ward: 'Pediatrics Ward',    room: '402', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'Viral Gastroenteritis',     medications: 'Oral rehydration salts',         allergies: ['None'], notes: 'Hydration monitoring.' },
  { id: 21, name: 'Isabel Gutierrez',    dob: '2012-06-30', gender: 'F', department: 'Pediatrics',    ward: 'Pediatrics Ward',    room: '403', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'Asthma',                     medications: 'Salbutamol',                     allergies: ['None'], notes: 'Pediatric pulmonary review.' },
  { id: 22, name: 'Fernando Dela Pena',  dob: '2010-02-14', gender: 'M', department: 'Pediatrics',    ward: 'Pediatrics Ward',    room: '404', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Fractured Wrist',           medications: 'Analgesics',                     allergies: ['None'], notes: 'Ortho follow-up.' },
  { id: 23, name: 'Lucia Ramos',         dob: '2008-09-08', gender: 'F', department: 'Pediatrics',    ward: 'Pediatrics Ward',    room: '405', status: 'Outpatient', physician: 'Dr. Santos',   diagnosis: 'Migraine',                  medications: 'Sumatriptan',                    allergies: ['None'], notes: 'Neuro consult PRN.' },
  { id: 24, name: 'Rafael Villar',       dob: '2005-12-01', gender: 'M', department: 'Pediatrics',    ward: 'Pediatrics Ward',    room: '406', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'Strep Throat',               medications: 'Penicillin V',                   allergies: ['None'], notes: 'Complete antibiotic course.' },
  { id: 25, name: 'Angelica Santiago',   dob: '2003-03-17', gender: 'F', department: 'Pediatrics',    ward: 'Pediatrics Ward',    room: '407', status: 'Outpatient', physician: 'Dr. Tan',      diagnosis: 'Anemia',                     medications: 'Iron supplements',                allergies: ['None'], notes: 'Repeat CBC in 1 month.' },
  { id: 26, name: 'Victor Manalo',       dob: '1976-10-03', gender: 'M', department: 'Neurology',     ward: 'Neurology Ward',     room: '501', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Epilepsy',                  medications: 'Levetiracetam 500mg',            allergies: ['None'], notes: 'Seizure diary.' },
  { id: 27, name: 'Kristine Ocampo',     dob: '1982-05-26', gender: 'F', department: 'Neurology',     ward: 'Neurology Ward',     room: '502', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Migraine',                  medications: 'Topiramate',                     allergies: ['None'], notes: 'Headache diary.' },
  { id: 28, name: 'Eduardo Salazar',     dob: '1953-09-12', gender: 'M', department: 'Neurology',     ward: 'Neurology Ward',     room: '503', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Parkinson Disease',         medications: 'Levodopa',                       allergies: ['None'], notes: 'Neuro rehab.' },
  { id: 29, name: 'Melissa Tuazon',      dob: '1991-07-07', gender: 'F', department: 'Neurology',     ward: 'Neurology Ward',     room: '504', status: 'Outpatient', physician: 'Dr. Bautista', diagnosis: 'Multiple Sclerosis',        medications: 'Interferon',                     allergies: ['None'], notes: 'Neuro follow-up quarterly.' },
  { id: 30, name: 'Paolo Ignacio',       dob: '1984-01-28', gender: 'M', department: 'Neurology',     ward: 'Neurology Ward',     room: '505', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Stroke (CVA)',               medications: 'Anticoagulants',                  allergies: ['None'], notes: 'Speech therapy.' },
  { id: 31, name: 'Grace Antonio',       dob: '1966-04-15', gender: 'F', department: 'Neurology',     ward: 'Neurology Ward',     room: '506', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Peripheral Neuropathy',     medications: 'Gabapentin',                     allergies: ['None'], notes: 'Podiatry consult.' },
  { id: 32, name: 'Dennis Bautista',     dob: '1979-08-19', gender: 'M', department: 'Gastroenterology', ward: 'Gastro Ward',     room: '601', status: 'Admitted',   physician: 'Dr. Mercado',  diagnosis: 'GERD',                      medications: 'PPIs',                           allergies: ['None'], notes: 'Endoscopy scheduled.' },
  { id: 33, name: 'Rowena Dizon',        dob: '1987-02-02', gender: 'F', department: 'Gastroenterology', ward: 'Gastro Ward',     room: '602', status: 'Admitted',   physician: 'Dr. Mercado',  diagnosis: 'Peptic Ulcer',               medications: 'Omeprazole',                     allergies: ['None'], notes: 'H. pylori test.' },
  { id: 34, name: 'Christopher Tan',     dob: '1968-06-06', gender: 'M', department: 'Gastroenterology', ward: 'Gastro Ward',     room: '603', status: 'Admitted',   physician: 'Dr. Mercado',  diagnosis: 'Hepatitis B',                medications: 'Antivirals',                     allergies: ['None'], notes: 'Liver function monitoring.' },
  { id: 35, name: 'Michelle Abad',       dob: '1993-10-10', gender: 'F', department: 'Gastroenterology', ward: 'Gastro Ward',     room: '604', status: 'Outpatient', physician: 'Dr. Mercado',  diagnosis: 'Irritable Bowel Syndrome',  medications: 'Antispasmodics',                 allergies: ['None'], notes: 'Dietary consult.' },
  { id: 36, name: 'Jonathan Castro',     dob: '1973-03-21', gender: 'M', department: 'Orthopedics',   ward: 'Ortho Ward',         room: '701', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Hip Fracture',              medications: 'Analgesics',                     allergies: ['None'], notes: 'Post-op rehab.' },
  { id: 37, name: 'Evelyn Marquez',      dob: '1961-12-12', gender: 'F', department: 'Orthopedics',   ward: 'Ortho Ward',         room: '702', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Knee Replacement',         medications: 'NSAIDs',                         allergies: ['None'], notes: 'Physical therapy.' },
  { id: 38, name: 'Noel Corpuz',         dob: '1996-08-08', gender: 'M', department: 'Orthopedics',   ward: 'Ortho Ward',         room: '703', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Sports Injury',             medications: 'Anti-inflammatories',             allergies: ['None'], notes: 'RICE protocol.' },
  { id: 39, name: 'Cherry Valdez',       dob: '1989-05-05', gender: 'F', department: 'Orthopedics',   ward: 'Ortho Ward',         room: '704', status: 'Outpatient', physician: 'Dr. Bautista', diagnosis: 'Carpal Tunnel',             medications: 'Wrist splint',                    allergies: ['None'], notes: 'Nerve conduction study.' },
  { id: 40, name: 'Alvin Domingo',       dob: '1959-09-09', gender: 'M', department: 'Orthopedics',   ward: 'Ortho Ward',         room: '705', status: 'Admitted',   physician: 'Dr. Bautista', diagnosis: 'Osteoporosis',              medications: 'Calcium + Vit D',                 allergies: ['None'], notes: 'Bone density scan.' },
  { id: 41, name: 'Weng Sy',             dob: '1970-11-11', gender: 'F', department: 'General Medicine', ward: 'General Ward',    room: '801', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Dengue Fever',               medications: 'Paracetamol',                    allergies: ['None'], notes: 'Platelet monitoring.' },
  { id: 42, name: 'Dante Ferrer',        dob: '1983-04-04', gender: 'M', department: 'General Medicine', ward: 'General Ward',    room: '802', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Cellulitis',                 medications: 'IV antibiotics',                 allergies: ['None'], notes: 'Wound care.' },
  { id: 43, name: 'Norma Villanueva',    dob: '1957-07-07', gender: 'F', department: 'General Medicine', ward: 'General Ward',    room: '803', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Urinary Tract Infection',   medications: 'Antibiotics',                    allergies: ['None'], notes: 'Urinalysis follow-up.' },
  { id: 44, name: 'Jessie Alcantara',    dob: '1990-12-12', gender: 'M', department: 'General Medicine', ward: 'General Ward',    room: '804', status: 'Admitted',   physician: 'Dr. Santos',   diagnosis: 'Malaria',                    medications: 'Antimalarials',                  allergies: ['None'], notes: 'Blood smear review.' },
  { id: 45, name: 'Lorna Miranda',       dob: '1963-06-06', gender: 'F', department: 'General Medicine', ward: 'General Ward',    room: '805', status: 'Outpatient', physician: 'Dr. Santos',   diagnosis: 'Dehydration',                medications: 'IV fluids',                      allergies: ['None'], notes: 'Electrolyte panel.' },
  { id: 46, name: 'Henry Lao',           dob: '1977-02-02', gender: 'M', department: 'Dermatology',    ward: 'Dermatology Ward',    room: '901', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'Eczema',                     medications: 'Topical steroids',               allergies: ['None'], notes: 'Skin care regimen.' },
  { id: 47, name: 'Arnel Soriano',       dob: '1981-10-10', gender: 'M', department: 'Dermatology',    ward: 'Dermatology Ward',    room: '902', status: 'Admitted',   physician: 'Dr. Tan',      diagnosis: 'Psoriasis',                  medications: 'Phototherapy',                   allergies: ['None'], notes: 'Derm follow-up.' },
  { id: 48, name: 'Divina Cabrera',      dob: '1994-08-08', gender: 'F', department: 'Dermatology',    ward: 'Dermatology Ward',    room: '903', status: 'Outpatient', physician: 'Dr. Tan',      diagnosis: 'Acne Vulgaris',              medications: 'Topical retinoids',              allergies: ['None'], notes: 'Review in 6 weeks.' },
  { id: 49, name: 'Gloria Pangilinan',   dob: '1951-01-01', gender: 'F', department: 'Nephrology',     ward: 'Nephrology Ward',     room: '1001', status: 'Admitted',  physician: 'Dr. Mercado',  diagnosis: 'Chronic Kidney Disease',    medications: 'Dialysis 3x/week',               allergies: ['None'], notes: 'Nephro consult.' },
  { id: 50, name: 'Samson Reyes',        dob: '1967-05-05', gender: 'M', department: 'Nephrology',     ward: 'Nephrology Ward',     room: '1002', status: 'Admitted',  physician: 'Dr. Mercado',  diagnosis: 'Kidney Stones',              medications: 'Analgesics',                     allergies: ['None'], notes: 'Urology consult.' },
];

// ---------------------------------------------------------------------------
// NOTES — seeded clinical observations (safe content; the stored-XSS lab is
// for users to experiment with). authorUid is filled in by the seed script.
// ---------------------------------------------------------------------------
const NOTES = [
  { patient: 'P-001', author: 'Dr. Santos',   content: 'Patient reports chest discomfort. ECG scheduled.', minutesAgo: 55 },
  { patient: 'P-002', author: 'Dr. Santos',   content: 'Fasting glucose elevated despite compliance. Intensify treatment, refer to dietitian.', minutesAgo: 130 },
  { patient: 'P-003', author: 'Nurse Reyes',  content: 'Patient using salbutamol inhaler 2x today. Peak flow stable.', minutesAgo: 200 },
  { patient: 'P-005', author: 'Dr. Santos',   content: 'Mild ST depression on ECG. Cardiology consult requested.', minutesAgo: 260 },
  { patient: 'P-006', author: 'Nurse Reyes',  content: 'INR checked: 2.4. Within therapeutic range.', minutesAgo: 320 },
  { patient: 'P-015', author: 'Dr. Tan',      content: 'Oxygen saturation 94% on room air. Continue nebulizer PRN.', minutesAgo: 400 },
  { patient: 'P-019', author: 'Nurse Reyes',  content: 'Pediatric patient tolerating oral fluids well. Fever resolved.', minutesAgo: 480 },
  { patient: 'P-030', author: 'Dr. Bautista', content: 'Post-stroke speech therapy session completed. Progress noted.', minutesAgo: 620 },
];

// ---------------------------------------------------------------------------
// LAB REPORTS — includes the tests from data/lab-report.txt plus more.
// status: 'completed' | 'pending'
// ---------------------------------------------------------------------------
const LAB_REPORTS = [
  { reportId: 'LR-20260901-0001', patientId: 'P-001', patientName: 'Maria Santos',      test: 'Complete Blood Count',        result: 'WBC 7.2, Hb 13.2, PLT 245 — NORMAL',       reference: 'Standard ranges', status: 'completed', date: '2026-09-01', department: 'Laboratory', orderedBy: 'Dr. Santos' },
  { reportId: 'LR-20260901-0002', patientId: 'P-002', patientName: 'Juan Dela Cruz',    test: 'Fasting Blood Glucose',       result: '8.2 mmol/L — ELEVATED',                    reference: '3.9 – 6.1 mmol/L', status: 'completed', date: '2026-09-01', department: 'Laboratory', orderedBy: 'Dr. Santos' },
  { reportId: 'LR-20260901-0003', patientId: 'P-002', patientName: 'Juan Dela Cruz',    test: 'HbA1c',                       result: '7.9% — ELEVATED',                          reference: '< 5.7% Normal', status: 'completed', date: '2026-09-01', department: 'Laboratory', orderedBy: 'Dr. Santos' },
  { reportId: 'LR-20260901-0004', patientId: 'P-002', patientName: 'Juan Dela Cruz',    test: 'Total Cholesterol',           result: '6.1 mmol/L — BORDERLINE HIGH',             reference: '< 5.2 mmol/L', status: 'completed', date: '2026-09-01', department: 'Laboratory', orderedBy: 'Dr. Santos' },
  { reportId: 'LR-20260902-0005', patientId: 'P-003', patientName: 'Ana Reyes',         test: 'Chest X-Ray',                 result: 'Mild bronchial wall thickening. Consistent with asthma.', reference: 'Radiologist read', status: 'completed', date: '2026-09-02', department: 'Radiology', orderedBy: 'Dr. Tan' },
  { reportId: 'LR-20260902-0006', patientId: 'P-005', patientName: 'Rosario Garcia',     test: 'ECG',                         result: 'Mild ST depression V4-V6 — ischemic changes', reference: 'Cardiology read', status: 'completed', date: '2026-09-02', department: 'Cardiology', orderedBy: 'Dr. Santos' },
  { reportId: 'LR-20260902-0007', patientId: 'P-007', patientName: 'Liza Mendoza',       test: 'BNP',                         result: 'Pending',                                  reference: '< 100 pg/mL', status: 'pending', date: '2026-09-02', department: 'Laboratory', orderedBy: 'Dr. Santos' },
  { reportId: 'LR-20260902-0008', patientId: 'P-012', patientName: 'Ricardo Navarro',    test: 'HbA1c',                       result: 'Pending',                                  reference: '< 5.7% Normal', status: 'pending', date: '2026-09-02', department: 'Laboratory', orderedBy: 'Dr. Mercado' },
  { reportId: 'LR-20260903-0009', patientId: 'P-016', patientName: 'Marco Reyes',        test: 'Sputum Culture',              result: 'Pending',                                  reference: 'Culture & sensitivity', status: 'pending', date: '2026-09-03', department: 'Laboratory', orderedBy: 'Dr. Tan' },
  { reportId: 'LR-20260903-0010', patientId: 'P-022', patientName: 'Fernando Dela Pena', test: 'Wrist X-Ray',                 result: 'Distal radius fracture, non-displaced.',   reference: 'Radiologist read', status: 'completed', date: '2026-09-03', department: 'Radiology', orderedBy: 'Dr. Bautista' },
  { reportId: 'LR-20260903-0011', patientId: 'P-026', patientName: 'Victor Manalo',      test: 'MRI Brain',                   result: 'No acute intracranial abnormality.',       reference: 'Radiologist read', status: 'completed', date: '2026-09-03', department: 'Radiology', orderedBy: 'Dr. Bautista' },
  { reportId: 'LR-20260903-0012', patientId: 'P-030', patientName: 'Paolo Ignacio',      test: 'CT Head',                     result: 'Pending',                                  reference: 'Radiologist read', status: 'pending', date: '2026-09-03', department: 'Radiology', orderedBy: 'Dr. Bautista' },
  { reportId: 'LR-20260904-0013', patientId: 'P-034', patientName: 'Christopher Tan',    test: 'Liver Function Panel',        result: 'ALT 88, AST 72 — MILD ELEVATION',          reference: 'ALT < 40, AST < 40', status: 'completed', date: '2026-09-04', department: 'Laboratory', orderedBy: 'Dr. Mercado' },
  { reportId: 'LR-20260904-0014', patientId: 'P-041', patientName: 'Weng Sy',            test: 'Platelet Count',              result: 'Pending',                                  reference: '150 – 450 x10^9/L', status: 'pending', date: '2026-09-04', department: 'Laboratory', orderedBy: 'Dr. Santos' },
  { reportId: 'LR-20260904-0015', patientId: 'P-049', patientName: 'Gloria Pangilinan',  test: 'Serum Creatinine',            result: '212 µmol/L — ELEVATED',                    reference: '62 – 106 µmol/L', status: 'completed', date: '2026-09-04', department: 'Laboratory', orderedBy: 'Dr. Mercado' },
];

// ---------------------------------------------------------------------------
// ACTIVITY — dashboard recent-activity feed.
// ---------------------------------------------------------------------------
const ACTIVITY = [
  { type: 'lab',       text: 'Lab results uploaded for Patient P-002 (Juan Dela Cruz)', minutesAgo: 10,  dept: 'Lab Department' },
  { type: 'admission', text: 'New patient admitted to Cardiology Ward — Room 103',        minutesAgo: 25,  dept: 'Admissions' },
  { type: 'treatment', text: 'Dr. Santos updated treatment plan for Maria Santos (P-001)', minutesAgo: 60, dept: 'Dr. Santos' },
  { type: 'discharge', text: 'Discharge summary completed for Ana Reyes (P-003)',        minutesAgo: 120, dept: 'Nursing Staff' },
  { type: 'system',    text: 'System backup completed successfully',                     minutesAgo: 130, dept: 'System' },
  { type: 'lab',       text: 'Chest X-Ray uploaded for Patient P-003 (Ana Reyes)',       minutesAgo: 200, dept: 'Radiology' },
  { type: 'admission', text: 'New patient admitted to Pediatrics Ward — Room 402',       minutesAgo: 260, dept: 'Admissions' },
  { type: 'note',      text: 'Clinical note added for Patient P-005 (Rosario Garcia)',   minutesAgo: 320, dept: 'Dr. Santos' },
];

module.exports = { STAFF, PATIENTS, NOTES, LAB_REPORTS, ACTIVITY };